name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install Node 18
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Npm Install
        run: npm install
        
      - name: Lint
        run: npm run lint
        
      - name: Test
        run: npm test
        
        # Generate sonar-project.properties dynamically
      - name: Generate sonar-project.properties
        run: |
          echo "sonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}" > sonar-project.properties
          echo "sonar.organization=${{ secrets.SONAR_ORGANIZATION }}" >> sonar-project.properties
          echo "sonar.sources=." >> sonar-project.properties
          echo "sonar.sourceEncoding=UTF-8" >> sonar-project.properties

      - name: Check Path
        run: ls -la && pwd && ls -la /

      - name: SonarCloud Scan 
        uses: SonarSource/sonarcloud-github-action@master 
        with: 
          args: > 
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} 
            -Dsonar.pullrequest.branch=${{ github.head_ref }} 
            -Dsonar.pullrequest.base=${{ github.base_ref }} 
            -Dsonar.pullrequest.github.repository=${{ github.repository }} 
            -Dsonar.pullrequest.provider=GitHub 
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
#       - name : Check Path
#         run: ls -la && pwd && ls -la /
      
      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@master
      #   if: success() || failure()
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
